cluster:
  name: vivo-br

cloudprovider: openstack

cloudCredentialSecretName: starazona

nodepools:
  - etcd: true
    controlplane: true
    worker: true
    labels: {}
    quantity: 1
    name: nodepool-1
    authUrl: "https://whitecloud.intra.whitestack.com:5000"
    domainName: Default
    flavorName: m1.large
    imageName: "Ubuntu-20.04-CRUISER"
    keypairName: CRUISER_DEPO_KP
    netName: intra-net-solutions-cruiser-mgmt
    privateKeyFile: |
      -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAqNwD2sxT9Yo6zFrRrpJvaGujaLdfo4G9NIjBajSTqw3ZYoA9XjiS
zfdyLNivWXThjQ/zgm/LtYR6otQ+QhGQKQTAD6R4Ay8nZdlnOtzFBZ348kE4Xq+mbKR0E7
4QfBim2Bz6nvURSA4Z/42QoozxC6OPHUj2ikCxp7WT0H8juBg5ChbQlGmwwdtjBiPtkSfJ
vJQeRxCPDdN6jAjKKrWvqWukMYpPYme0LAHX2d38ChcxSR4ZrgP5njs/IdwViQL6jQWVfi
SYskdlWMxtS6bwvcTuLKpMJS9HZGnhDc/IYE8yVaj2IZR9LTZX+0EErd2Vb5b3eL0cxihU
QRTPlrmnNW+l40Q9bfHr80Lm3Poz2H1anrEUxTGbcCkPumpT8hZ8A9HQcJ6xQQNWnoGNyH
ERvj7rfXdChbZLexvDJvzfbM3bzFqtBDVa+kb3TCdJSgRLBzOeJ9O2CNXuoL3eFJKLHGsd
3QEn/STHj8lOgSgrO3o1T21ddVXTXIjARCHYYVHtAAAFkI6MWHmOjFh5AAAAB3NzaC1yc2
EAAAGBAKjcA9rMU/WKOsxa0a6Sb2hro2i3X6OBvTSIwWo0k6sN2WKAPV44ks33cizYr1l0
4Y0P84Jvy7WEeqLUPkIRkCkEwA+keAMvJ2XZZzrcxQWd+PJBOF6vpmykdBO+EHwYptgc+p
71EUgOGf+NkKKM8Qujjx1I9opAsae1k9B/I7gYOQoW0JRpsMHbYwYj7ZEnybyUHkcQjw3T
eowIyiq1r6lrpDGKT2JntCwB19nd/AoXMUkeGa4D+Z47PyHcFYkC+o0FlX4kmLJHZVjMbU
um8L3E7iyqTCUvR2Rp4Q3PyGBPMlWo9iGUfS02V/tBBK3dlW+W93i9HMYoVEEUz5a5pzVv
peNEPW3x6/NC5tz6M9h9Wp6xFMUxm3ApD7pqU/IWfAPR0HCesUEDVp6BjchxEb4+6313Qo
W2S3sbwyb832zN28xarQQ1WvpG90wnSUoESwcznifTtgjV7qC93hSSixxrHd0BJ/0kx4/J
ToEoKzt6NU9tXXVV01yIwEQh2GFR7QAAAAMBAAEAAAGAEDTdodhOjphvwEFPMqQXUTxTeK
9w3G6NTEd72MenDJnNrWiFe0+Ot3nyWV+KpNlU9Ib9Zh14vbkzVAFu4ERzQ5yTGm08n4Gd
FGdjQwEBX+KjjAy6bkwJew/lnCd3yZFMIh3V5/+5YuMHl8Fsik1grS9LgxIHp4lCA8inoT
Eyqm6YuuEpr7TdJB38SRCVsoLRF+pXZZavRDJx5pLJZIP/khEktySBLf6qCjc7Ekv97rH/
Jvdem5cCFC+3hXZsErRYU9hUJEKkQ01eej6ofucXVUZNCyMUzf9KFjYNIXD9BX3yYJsYyH
AU0Bux0ypieMqsYkcnYe4gC8cZe3ZrLHrGpUCp4DkNUgt3pgljBjAaeRmbvFBxWEXx3WKp
J+qzCkWVKDYSBNwuHtBep97ZS3CWiSb5FlBLHtWwZvrUbQvG7RtMe7xaje4NOgorIgZEKF
rog9UdNNFJNR//CesM2GMFrxvdTQmG1tdAXff7nhlnH3GRLuqoAbjMfPF/S99ypV1BAAAA
wQDQ23DW+EB9JzrdpE1Uld8UKxIoeduhUsVdUxEpuFH/h3KVe4eVaC209N5Z5/H2SpR4I5
DO7WH0xGheEtllasfEqtKbCJcRmPEKIJ4Eq8No8sKe8z5LkG6rXXYUtmQjL6FkTQwuLZpR
afDPskH49Pg+c5997VazIW+Y7cdWwBIatWC9p09+iKaZqUNi56LzE0r8zq0BBrlxoFjrd3
yzlY5IOSMB/wQD3GwoWGj6WsBiSpd44NZ2RQkUOYE/pYGEZpAAAADBANVC/qFWXBjcogOL
nQx6LLfBi5dpIN6mO9Bao9nlpQA4lz/0gCH8/cuxsL9xf9Evxb368kj9BG09af8j6T6K+T
5Ihv3W9RXy+AhtlPP8ASJk89N5k5M1uxSCVsILhSIgitxxrTwA4QkkJYNINXaWxDE6CiE2
AMTurESANjFoK9PG8XOgmYWXo0fxgg8XOUtVPB8YgBfWf+Jafd0QJ8DMrzhSfLUggNt7lB
F4ADwwzzGyohJud70p1a9cH6j7z/sFJQAAAMEAyrMK6eEEwwblNfMg7lzIFBwy5/NvcaxJ
n/Ar4qxrOyzVQzp3+I5pUGdaMfPrS6kfq5rQJtEG7pBZGacLgdxW3gdUQgVvnWWw3Vw8hP
0xxFY7Fe8Syfwdbz8+CLzI6X6iXjBD+LLbFdO8c6S+i5HHAkDxbM3bJPL1D+SW+ffYwtti
NI02pb6OQsKl025lhRyV/7oMKE6w4iOvhsnYX/z2laVaDsXgqmhbvH4Cuk1ZPHaOvdteqb
s+pLWcuXrpMNMpAAAAE3VidW50dUBjcnVpc2VyLWRlcG8BAgMEBQYH
-----END OPENSSH PRIVATE KEY-----
    region: RegionOne
    secGroups: default
    sshPort: 22
    sshUser: ubuntu
    tenantName: team-solutions-downstreamclusters
    username: starazona
    availabilityZone: HAL1
    cacert: |
      -----BEGIN CERTIFICATE-----
MIIFjDCCA3SgAwIBAgIQfx8skC6D0OO2+zvuR4tegDANBgkqhkiG9w0BAQsFADBM
MSAwHgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSNjETMBEGA1UEChMKR2xv
YmFsU2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjAeFw0yMzA3MTkwMzQzMjVaFw0y
NjA3MTkwMDAwMDBaMFUxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWdu
IG52LXNhMSswKQYDVQQDEyJHbG9iYWxTaWduIEdDQyBSNiBBbHBoYVNTTCBDQSAy
MDIzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA00Jvk5ADppO0rgDn
j1M14XIb032Aas409JJFAb8cUjipFOth7ySLdaWLe3s63oSs5x3eWwzTpX4BFkzZ
bxT1eoJSHfT2M0wZ5QOPcCIjsr+YB8TAvV2yJSyq+emRrN/FtgCSTaWXSJ5jipW8
SJ/VAuXPMzuAP2yYpuPcjjQ5GyrssDXgu+FhtYxqyFP7BSvx9jQhh5QV5zhLycua
n8n+J0Uw09WRQK6JGQ5HzDZQinkNel+fZZNRG1gE9Qeh+tHBplrkalB1g85qJkPO
J7SoEvKsmDkajggk/sSq7NPyzFaa/VBGZiRRG+FkxCBniGD5618PQ4trcwHyMojS
FObOHQIDAQABo4IBXzCCAVswDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsG
AQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBS9
BbfzipM8c8t5+g+FEqF3lhiRdDAfBgNVHSMEGDAWgBSubAWjkxPioufi1xzWx/B/
yGdToDB7BggrBgEFBQcBAQRvMG0wLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwMi5n
bG9iYWxzaWduLmNvbS9yb290cjYwOwYIKwYBBQUHMAKGL2h0dHA6Ly9zZWN1cmUu
Z2xvYmFsc2lnbi5jb20vY2FjZXJ0L3Jvb3QtcjYuY3J0MDYGA1UdHwQvMC0wK6Ap
oCeGJWh0dHA6Ly9jcmwuZ2xvYmFsc2lnbi5jb20vcm9vdC1yNi5jcmwwIQYDVR0g
BBowGDAIBgZngQwBAgEwDAYKKwYBBAGgMgoBAzANBgkqhkiG9w0BAQsFAAOCAgEA
fMkkMo5g4mn1ft4d4xR2kHzYpDukhC1XYPwfSZN3A9nEBadjdKZMH7iuS1vF8uSc
g26/30DRPen2fFRsr662ECyUCR4OfeiiGNdoQvcesM9Xpew3HLQP4qHg+s774hNL
vGRD4aKSKwFqLMrcqCw6tEAfX99tFWsD4jzbC6k8tjSLzEl0fTUlfkJaWpvLVkpg
9et8tD8d51bymCg5J6J6wcXpmsSGnksBobac1+nXmgB7jQC9edU8Z41FFo87BV3k
CtrWWsdkQavObMsXUPl/AO8y/jOuAWz0wyvPnKom+o6W4vKDY6/6XPypNdebOJ6m
jyaILp0quoQvhjx87BzENh5s57AIOyIGpS0sDEChVDPzLEfRsH2FJ8/W5woF0nvs
BTqfYSCqblQbHeDDtCj7Mlf8JfqaMuqcbE4rMSyfeHyCdZQwnc/r9ujnth691AJh
xyYeCM04metJIe7cB6d4dFm+Pd5ervY4x32r0uQ1Q0spy1VjNqUJjussYuXNyMmF
HSuLQQ6PrePmH5lcSMQpYKzPoD/RiNVD/PK0O3vuO5vh3o7oKb1FfzoanDsFFTrw
0aLOdRW/tmLPWVNVlAb8ad+B80YJsL4HXYnQG8wYAFb8LhwSDyT9v+C1C1lcIHE7
nE0AAp9JSHxDYsma9pi4g0Phg3BgOm2euTRzw7R0SzU=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEijCCA3KgAwIBAgIQfU1CqStDHX5kU+fBmo1YdzANBgkqhkiG9w0BAQsFADBX
MQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEQMA4GA1UE
CxMHUm9vdCBDQTEbMBkGA1UEAxMSR2xvYmFsU2lnbiBSb290IENBMB4XDTIyMTAx
MjAzNDk0M1oXDTI3MTAxMjAwMDAwMFowTDELMAkGA1UEBhMCQkUxGTAXBgNVBAoT
EEdsb2JhbFNpZ24gbnYtc2ExIjAgBgNVBAMTGUFscGhhU1NMIENBIC0gU0hBMjU2
IC0gRzQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCtJCmVZhWIPzOH
A3jP1QwkuDFT8/+DImyZlSt85UpZwq7G0Sqd+n8gLlHIZypQkad5VkT7OLU+MI78
lC7LVwxpU19ExlaWL67ANyWG8XHx3AJFQoZhuDbvUeNzRQyQs6XS5wN6uDlF0Bf1
AtCUQWrGGLGYwyC1xTrzgrFKpESsIXMqklUGTsh8i7DKZhRUVfgrPLJUkbbLUrLY
42+KRCiwfSvBloC5PgDYnj3oMZ1aTe3Wfk3l1I4D3RKaJ4PU1qHXhHJOge2bjGIG
l6MsaBN+BB2sr6EnxX0xnMIbew2oIfOFoLqs47vh/GH4JN0qql2WBHfDPVDm3b+G
QxY6N/LXAgMBAAGjggFbMIIBVzAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYE
FE/LrKjC76vdg29rv86YPVxYJXYVMB8GA1UdIwQYMBaAFGB7ZhpFDZfKiVAvfQTN
NKj//P1LMHoGCCsGAQUFBwEBBG4wbDAtBggrBgEFBQcwAYYhaHR0cDovL29jc3Au
Z2xvYmFsc2lnbi5jb20vcm9vdHIxMDsGCCsGAQUFBzAChi9odHRwOi8vc2VjdXJl
Lmdsb2JhbHNpZ24uY29tL2NhY2VydC9yb290LXIxLmNydDAzBgNVHR8ELDAqMCig
JqAkhiJodHRwOi8vY3JsLmdsb2JhbHNpZ24uY29tL3Jvb3QuY3JsMCEGA1UdIAQa
MBgwCAYGZ4EMAQIBMAwGCisGAQQBoDIKAQMwDQYJKoZIhvcNAQELBQADggEBABol
9nNkiECpWQenQ7oVP1FhvRX/LWTdzXpdMmp/SELnEJhoOe+366E0dt8tWGg+ezAc
DPeGYPmp83nAVLeDpji7Nqu8ldB8+G/B6U9GB8i2DDIAqSsFEvcMbWb5gZ2/DmRN
cifGi9FKAuFu2wyft4s4DHwzL2CJ2zjMlUOM3RaE1cxuOs+Om6MCD9G7vnkAtSiC
/OOfHO902f4yI2a48K+gKaAf3lISFXjd32pwQ21LpM3ueIGydaJ+1/z8nv+C7SUT
5bHoz7cYU27LUvh1n2WSNnC6/QwFSoP6gNKa4POO/oO13xjhrLRHJ/04cKMbRALt
JWQkPacJ8SJVhB2R7BI=
-----END CERTIFICATE-----
